# Generated by Django 3.1.7 on 2021-03-28 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudySpaceApi', '0002_auto_20210327_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='groupName',
        ),
    ]
