# Generated by Django 3.1.7 on 2021-03-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudySpaceApi', '0003_auto_20210327_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='picture',
            field=models.ImageField(null=True, upload_to='group'),
        ),
    ]
