# Generated by Django 3.1.7 on 2021-04-05 01:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StudySpaceApi', '0004_auto_20210327_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='StudySpaceApi.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='picture',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
        migrations.AddField(
            model_name='posts',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='upvotes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
