# Generated by Django 3.1.7 on 2021-04-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudySpaceApi', '0006_auto_20210404_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='upvotes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
