# Generated by Django 3.1.7 on 2021-04-05 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudySpaceApi', '0007_responses_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='response_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StudySpaceApi.responses'),
        ),
    ]
