# Generated by Django 3.1.7 on 2021-04-05 02:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StudySpaceApi', '0008_auto_20210404_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
