# Generated by Django 3.2 on 2021-04-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudySpaceApi', '0009_responses_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='online_status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
