# Generated by Django 3.2 on 2021-04-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudySpaceApi', '0010_user_online_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='tags',
            field=models.CharField(default='Data Science, Computer Science', max_length=50),
            preserve_default=False,
        ),
    ]
