# Generated by Django 3.2 on 2021-04-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudySpaceApi', '0011_group_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
    ]
